#_welcome:
#    resource: "@AcmeDemoBundle/Controller/WelcomeController.php"
#    type:     annotation

homepage:
  pattern: /
  defaults: { _controller: TumfTepcoBundle:Default:index }

data:
  pattern: /current.{_format}
  defaults: { _controller: TumfTepcoBundle:Data:index,_format:html }
  requirements:
    _format: html|json|xml
    

