_welcome:
    resource: "@AcmeDemoBundle/Controller/WelcomeController.php"
    type:     annotation
_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /_demo
_configurator:
    resource: "@SymfonyWebConfiguratorBundle/Resources/config/routing/configurator.xml"
    prefix:   /_configurator
