_welcome:
    resource: "@AcmeDemoBundle/Controller/WelcomeController.php"
    type:     annotation
_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /_demo
